//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildWebSite
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GuilRecruitment
    {
        public int RcruitID { get; set; }
        [Display(Name = "Character Name")]
        public string CharacterName { get; set; }
        [Display(Name = "Realm")]
        public string Realm { get; set; }
        public string Class { get; set; }
        public string Specialization { get; set; }
        public string Offspec { get; set; }
        [Display(Name = "Our raid times are 8:30-11:30 Tuesday and Thursday please list any limitations reguarding attendance")]
        [DataType(DataType.MultilineText)]
        public string RaidTimes { get; set; }
        [Display(Name = "Raiding experience")]
        [DataType(DataType.MultilineText)]
        public string RaidingExperience { get; set; }
        [Display(Name = "Combat Logs")]
        [DataType(DataType.MultilineText)]
        public string CombatLogs { get; set; }
        [Display(Name = "Armory Link")]
        [DataType(DataType.MultilineText)]
        public string ArmoryLink { get; set; }
        public int Age { get; set; }
        [Display(Name = "Tell Us More")]
        [DataType(DataType.MultilineText)]
        public string TellUsMore { get; set; }
        [Display(Name = "This is a raiding guild wiping comes with the territory is that something you can handle?")]
        public string hardcore { get; set; }
        [Display(Name = "BattleTag")]
        public string BattleTag { get; set; }
        [Display(Name = "Why are you Leaving your last Guild?")]
        [DataType(DataType.MultilineText)]
        public string Why { get; set; }
        [Display(Name = "Why Hellscream's Angels")]
        [DataType(DataType.MultilineText)]
        public string Reasons { get; set; }
    }
}
